version: "3.8"
volumes:
  repo-volume:

services:
  update-service:
    image: update-service:latest
    ports:
      - "3001:3001"
    volumes:
      - repo-volume:/app
    env_file:
      - ./packages/update-service/.env
      - ./packages/update-service/docker.env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
  runner-service:
    image: runner-service:latest
    volumes:
      - repo-volume:/app:ro
    restart: always
    depends_on:
      - update-service

  # runner-service:
  #   build: ./packages/runner
  #   restart: on-failure
  #   depends_on:
  #     - update-service
