on:
  push:
    branches:
      - develop
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    #   - "@org/*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release1

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    # if: contains(github.ref ,'@org')
    steps:
      # - name: Extract Branch Name
      #   run: printenv
      - name: Hello world action step
        id: hello
        uses: bdurrani/github-action@v1.2
        with:
          who-to-greet: "Mona the Octocat"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  # build:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         draft: false
  #         prerelease: false
